FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install
RUN npm install -g serve

COPY . ./

RUN npx tailwindcss -i ./style.css -o ./output.css --minify

CMD ["serve", "-s", ".", "-l", "8000"]
